[tool.poetry]
name = "invoicing"
version = "0.1.0"
description = ""
authors = ["Elsa <elsaryynanen@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.2.2"
flask-sqlalchemy = "^3.0.2"
psycopg2-binary = "^2.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
